import { type ChangeEvent, useEffect, useRef, useState } from 'react';
import { Camera, Check, ChevronLeft, ChevronRight, FlipHorizontal2, ImagePlus, Loader2, Trash2 } from 'lucide-react';
import { useLocation } from 'wouter';
import { getListStripsQueryKey, useCreateStrip } from '@workspace/api-client-react';
import { useQueryClient } from '@tanstack/react-query';
import type { StripInput } from '@workspace/api-client-react';
import { AppShell, BackLink, PrimaryButton, StripPreview, ToastMessage } from '@/components/larapel';
type Step = 'capture' | 'style' | 'note';
const filters = ['mono', 'sepia'] as const;
export default function Create() {
  const [, setLocation] = useLocation(); const queryClient = useQueryClient(); const fileRef = useRef<HTMLInputElement>(null); const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null); const startedCamera = useRef(false);
  const [photos, setPhotos] = useState<string[]>([]); const [step, setStep] = useState<Step>('capture'); const [note, setNote] = useState(''); const [placement, setPlacement] = useState<'front' | 'back'>('front'); const [filter, setFilter] = useState<'mono' | 'sepia'>('mono'); const [toast, setToast] = useState(''); const [cameraOpen, setCameraOpen] = useState(false); const createStrip = useCreateStrip();
  const stopCamera = () => { streamRef.current?.getTracks().forEach(t => t.stop()); streamRef.current = null; setCameraOpen(false); };
  useEffect(() => () => { streamRef.current?.getTracks().forEach(t => t.stop()); }, []);
  const openCamera = async () => { if (!navigator.mediaDevices?.getUserMedia) return fileRef.current?.click(); try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); streamRef.current = stream; setCameraOpen(true); requestAnimationFrame(() => { if (videoRef.current) { videoRef.current.srcObject = stream; void videoRef.current.play(); } }); } catch { fileRef.current?.click(); } };
  useEffect(() => { if (!startedCamera.current) { startedCamera.current = true; void openCamera(); } }, [openCamera]);
  const capture = () => { const video = videoRef.current; if (!video || !video.videoWidth || photos.length >= 3) return; const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d')?.drawImage(video, 0, 0, canvas.width, canvas.height); setPhotos(current => [...current, canvas.toDataURL('image/jpeg', .9)]); stopCamera(); };
  const addPhoto = (file: File) => { if (photos.length >= 3) return; const reader = new FileReader(); reader.onload = () => setPhotos(current => current.length < 3 ? [...current, String(reader.result)] : current); reader.readAsDataURL(file); };
  const onFileChange = (event: ChangeEvent<HTMLInputElement>) => { Array.from(event.target.files || []).slice(0, 3 - photos.length).forEach(addPhoto); event.target.value = ''; };
  const save = () => createStrip.mutate({ data: { photos, note: note.trim(), placement, filter } as StripInput }, { onSuccess: strip => { queryClient.invalidateQueries({ queryKey: getListStripsQueryKey() }); setToast('saved'); setTimeout(() => setLocation(`/share/${strip.id}`), 300); }, onError: () => setToast('try again') });
  const stepIndex = ['capture', 'style', 'note'].indexOf(step);
  return <AppShell><div className="mx-auto min-h-[calc(100dvh-65px)] max-w-4xl px-4 pb-6 sm:px-6"><div className="pt-4"><BackLink href="/" /></div><div className="mt-4 flex gap-1" aria-label="progress">{[0,1,2].map(index => <span key={index} className={`h-1 flex-1 ${stepIndex >= index ? 'bg-accent' : 'bg-muted'}`} />)}</div>
    {step === 'capture' ? <section className="relative mt-4 flex min-h-[calc(100dvh-130px)] flex-col"><div className="grid flex-1 gap-1 overflow-hidden bg-muted sm:grid-cols-3">{photos.length ? photos.map((photo, index) => <div key={photo} className="group relative min-h-40"><img src={photo} alt={`photo ${index + 1}`} className="h-full w-full object-cover grayscale" /><button onClick={() => setPhotos(current => current.filter((_, i) => i !== index))} className="absolute right-2 top-2 grid h-8 w-8 place-items-center bg-background" aria-label="remove photo"><Trash2 size={14} /></button></div>) : <div className="col-span-full grid min-h-[55vh] place-items-center"><Camera size={42} className="text-secondary" /></div>}</div><div className="flex items-center justify-between py-4"><button onClick={() => fileRef.current?.click()} disabled={photos.length >= 3} aria-label="photos" className="grid h-11 w-11 place-items-center border border-secondary text-secondary"><ImagePlus size={18} /></button><button onClick={openCamera} disabled={photos.length >= 3} aria-label="camera" className="grid h-16 w-16 place-items-center rounded-full border-[5px] border-background bg-accent"><Camera size={24} /></button><PrimaryButton onClick={() => setStep('style')} disabled={!photos.length} testId="button-next-style"><ChevronRight size={18} /></PrimaryButton></div><input ref={fileRef} type="file" accept="image/*" capture="environment" multiple onChange={onFileChange} className="hidden" />{cameraOpen ? <div className="fixed inset-0 z-50 flex flex-col bg-foreground p-4"><video ref={videoRef} muted playsInline className="min-h-0 flex-1 object-cover" /><div className="flex items-center justify-between py-5"><button onClick={stopCamera} aria-label="close camera" className="h-12 w-12 text-background"><ChevronLeft /></button><button onClick={capture} aria-label="capture" className="grid h-16 w-16 place-items-center rounded-full border-[5px] border-background bg-accent"><Camera size={23} /></button><span className="h-12 w-12" /></div></div> : null}</section> : null}
    {step === 'style' ? <section className="pt-6"><div className="grid grid-cols-2 gap-2">{filters.map(option => <button key={option} onClick={() => setFilter(option)} aria-label={`select ${option}`} className={`border p-1 ${filter === option ? 'border-2 border-accent' : 'border-border'}`}><img src={photos[0]} alt="" className={`aspect-square w-full object-cover ${option === 'mono' ? 'grayscale' : 'sepia'}`} /></button>)}</div><div className="mt-6 flex justify-between"><button onClick={() => setStep('capture')} aria-label="back" className="grid h-11 w-11 place-items-center border border-secondary"><ChevronLeft size={18} /></button><PrimaryButton onClick={() => setStep('note')} testId="button-next-note">next <ChevronRight size={16} /></PrimaryButton></div></section> : null}
    {step === 'note' ? <section className="flex flex-col items-center gap-5 pt-5"><StripPreview photos={photos} note={note} placement={placement} filter={filter} /><div className="flex w-full max-w-md border-b border-secondary"><textarea value={note} onChange={event => setNote(event.target.value.slice(0, 180))} placeholder="add a note" aria-label="add a note" className="min-h-14 flex-1 resize-none bg-transparent py-3 text-base outline-none placeholder:text-secondary" /><button onClick={() => setPlacement(current => current === 'front' ? 'back' : 'front')} aria-label="toggle note placement" className="grid w-11 place-items-center text-secondary"><FlipHorizontal2 size={17} /></button></div><div className="flex w-full max-w-md items-center justify-between"><span className="border border-secondary px-2 py-1 text-[10px] font-bold text-secondary">free</span><div className="flex gap-2"><button onClick={() => setStep('style')} aria-label="back" className="grid h-11 w-11 place-items-center border border-secondary"><ChevronLeft size={18} /></button><PrimaryButton onClick={save} disabled={createStrip.isPending} testId="button-save-strip">{createStrip.isPending ? <Loader2 size={15} className="animate-spin" /> : <Check size={15} />}save</PrimaryButton></div></div></section> : null}</div>{toast ? <ToastMessage onClose={() => setToast('')}>{toast}</ToastMessage> : null}</AppShell>;
}
